data:api:
  - 'api\.'
  - '\/docs\/Web\/API'
data:css:
  - 'css\.'
  - '\/docs\/Web\/CSS'
data:html:
  - 'html\.'
  - '\/docs\/Web\/HTML'
data:http:
  - 'http\.'
  - '\/docs\/Web\/HTTP'
data:js:
  - 'js\.'
  - '\/docs\/Web\/JavaScript'
data:mathml:
  - 'mathml\.'
  - '\/docs\/Web\/MathML'
data:svg:
  - 'svg\.'
  - '\/docs\/Web\/SVG'
data:wasm:
  - 'webassembly\.'
  - '\/docs\/WebAssembly'
data:webdriver:
  - 'webdriver\.'
  - '\/docs\/Web\/WebDriver'
data:webext:
  - 'webextensions\.'
  - '\/docs\/Mozilla\/Add-ons'
