data:api :rabbit2::
  - 'api\.'
  - '\/docs\/Web\/API'
data:css :art::
  - 'css\.'
  - '\/docs\/Web\/CSS'
data:html :page_facing_up::
  - 'html\.'
  - '\/docs\/Web\/HTML'
data:http :mountain_cableway::
  - 'http\.'
  - '\/docs\/Web\/HTTP'
data:js :pager::
  - 'js\.'
  - '\/docs\/Web\/JavaScript'
data:mathml :heavy_division_sign::
  - 'mathml\.'
  - '\/docs\/Web\/MathML'
data:svg :paintbrush::
  - 'svg\.'
  - '\/docs\/Web\/SVG'
data:wasm :mechanical_arm::
  - 'webassembly\.'
  - '\/docs\/WebAssembly'
data:webdriver :racing_car::
  - 'webdriver\.'
  - '\/docs\/Web\/WebDriver'
data:webext :game_die::
  - 'webextensions\.'
  - '\/docs\/Mozilla\/Add-ons'
