bulk_update :package::
  - "scripts/migrations/**"
data:api :rabbit2::
  - "api/**"
data:browsers :earth_africa::
  - "browsers/**"
data:css :art::
  - "css/**"
data:html :page_facing_up::
  - "html/**"
data:http :mountain_cableway::
  - "http/**"
data:js :pager::
  - "javascript/**"
data:mathml :heavy_division_sign::
  - "mathml/**"
data:svg :paintbrush::
  - "svg/**"
data:webdriver :racing_car::
  - "webdriver/**"
data:webext :game_die::
  - "webext/**"
data:xpath :railway_track::
  - "xpath/**"
data:xslt :tractor::
  - "xslt/**"
dependencies :chains::
  - "package-lock.json"
  - "package.json"
docs :writing_hand::
  - "*.md"
infra :building_construction::
  - "/*.js"
  - "/*.ts"
  - ".editorconfig"
  - ".git*"
  - ".npm*"
  - ".travis.yml"
  - ".github/**"
  - "LICENSE"
  - "package*"
linter :house_with_garden::
  - "test/**"
schema :gear::
  - "schemas/**"
