/* This file is a part of @mdn/browser-compat-data
 * See LICENSE file for more information. */

export { default as testBrowsersData } from './test-browsers-data.js';
export { default as testBrowsersPresence } from './test-browsers-presence.js';
export { default as testConsistency } from './test-consistency.js';
export { default as testDescriptions } from './test-descriptions.js';
export { default as testFilename } from './test-filename.js';
export { default as testFlags } from './test-flags.js';
export { default as testLinks } from './test-links.js';
export { default as testMDNURLs } from './test-mdn-urls.js';
export { default as testMirror } from './test-mirror.js';
export { default as testMultipleStatements } from './test-multiple-statements.js';
export { default as testNotes } from './test-notes.js';
export { default as testObsolete } from './test-obsolete.js';
export { default as testPrefix } from './test-prefix.js';
export { default as testSchema } from './test-schema.js';
export { default as testSpecURLs } from './test-spec-urls.js';
export { default as testStatus } from './test-status.js';
export { default as testStatusInheritance } from './test-status-inheritance.js';
export { default as testStyle } from './test-style.js';
export { default as testTags } from './test-tags.js';
export { default as testVersions } from './test-versions.js';
