name: "Enhancement"
description: An enhancement to BCD's infrastructure
labels: ["enhancement :1st_place_medal:"]
body:
  - type: markdown
    attributes:
      value: |
        ### Issue etiquette

        When opening an issue, please:
        - Follow the project's [Code of Conduct](https://github.com/mdn/browser-compat-data/blob/main/CODE_OF_CONDUCT.md) as well as the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines). Failure to comply may result in exclusion from MDN Web Docs and/or GitHub.
        - Check for an [existing issue](https://github.com/mdn/browser-compat-data/issues) first. If someone else has opened an issue describing the same problem, please upvote their issue rather than creating another one.
        - Keep issues relevant to the project. Irrelevant issues will be automatically closed and marked as spam, and repeated offenses may result in exclusion from MDN Web Docs.
        - Provide as much detail as possible. The more detail you are able to provide, the better!
        - Write issues primarily in English. While translation tools are available, we will be able to provide better assistance with pre-translated content. You are more than welcome to include a version of the issue body in your preferred language alongside the English version.

        ---
  - type: textarea
    id: enhancement
    attributes:
      label: What would you like to see added to BCD?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: How impactful do you think this enhancement will be?
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, screenshots, screen recordings, or sample code
  - type: markdown
    attributes:
      value: |
        ---
        You're finished! Please click **Submit new issue**.
