/* This file is a part of @mdn/browser-compat-data
 * See LICENSE file for more information. */

/* c8 ignore start */

import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

import esMain from 'es-main';
import { compileFromFile } from 'json-schema-to-typescript';

import { spawn } from '../utils/index.js';

const dirname = fileURLToPath(new URL('.', import.meta.url));

const opts = {
  bannerComment:
    '/* This file is a part of @mdn/browser-compat-data\n * See LICENSE file for more information. */\n\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source schema files in\n* schemas/*, and run "npm run gentypes" to regenerate this file.\n*/',
  unreachableDefinitions: true,
};

/**
 * Transform the TypeScript to remove unneeded bits of typedefs
 * @param {string} ts Typedefs
 * @returns {string} Updated typedefs
 */
const transformTS = (ts) => {
  // Remove "interface was referenced" comments.
  ts = ts
    .replace(
      /( \*\n)? \* This interface was referenced by [^\n]+\n \* via the [^\n]+\n/g,
      '',
    )
    .replace(/\/\*\*\n \*\/\n/g, '');

  return ts;
};

/**
 * Compile the TypeScript typedefs from the schema JSON
 * @param {URL | string} [destination] Output destination
 */
const compile = async (
  destination = new URL('../types/types.d.ts', import.meta.url),
) => {
  let ts = await compileFromFile('schemas/public.schema.json', opts);

  ts = transformTS(ts);

  await fs.writeFile(destination, ts);
  spawn('tsc', ['--skipLibCheck', '../types/types.d.ts'], {
    cwd: dirname,
    stdio: 'inherit',
  });
};

if (esMain(import.meta)) {
  await compile();
}

export default compile;

/* c8 ignore stop */
