/* This file is a part of @mdn/browser-compat-data
 * See LICENSE file for more information. */

/* c8 ignore start */

import fs, { readFile, rm } from 'node:fs/promises';
import { basename, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import esMain from 'es-main';
import { compile } from 'json-schema-to-typescript';

import { spawn } from '../utils/index.js';

const root = new URL('..', import.meta.url);

const opts = {
  bannerComment:
    '/* This file is a part of @mdn/browser-compat-data\n * See LICENSE file for more information. */\n\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source schema files in\n* schemas/*, and run "npm run gentypes" to regenerate this file.\n*/',
  unreachableDefinitions: true,
};

/**
 * Transform the TypeScript to remove unneeded bits of typedefs
 * @param {string} ts Typedefs
 * @returns {string} Updated typedefs
 */
const transformTS = (ts) => {
  // Remove "interface was referenced" comments.
  ts = ts
    .replace(
      /( \*\n)? \* This interface was referenced by [^\n]+\n \* via the [^\n]+\n/g,
      '',
    )
    .replace(/\/\*\*\n \*\/\n/g, '');

  return ts;
};

/**
 * Append `examples` values to `description` strings throughout a schema.
 *
 * `json-schema-to-typescript` emits `description` as JSDoc but ignores the
 * sibling `examples` keyword. Inlining the examples ensures they appear in
 * the generated TypeScript declarations.
 * @param {*} node - Current schema node
 */
const injectExamplesIntoDescriptions = (node) => {
  if (node === null || typeof node !== 'object') {
    return;
  }
  if (Array.isArray(node)) {
    node.forEach(injectExamplesIntoDescriptions);
    return;
  }
  if (
    typeof node.description === 'string' &&
    Array.isArray(node.examples) &&
    node.examples.length > 0
  ) {
    const formatted = node.examples.map((e) => JSON.stringify(e)).join(', ');
    node.description = [node.description, `Examples: ${formatted}`].join(
      '\n\n',
    );
  }
  for (const value of Object.values(node)) {
    injectExamplesIntoDescriptions(value);
  }
};

/**
 * Load a JSON schema from disk and inline its `examples` into descriptions.
 * @param {string} source - Path to the schema file
 * @returns {Promise<string>} Generated TypeScript declarations
 */
const compileSchemaFile = async (source) => {
  const schema = JSON.parse(await readFile(source, 'utf-8'));
  injectExamplesIntoDescriptions(schema);
  return compile(schema, basename(source, '.json'), {
    ...opts,
    cwd: dirname(source),
  });
};

/**
 * Compile TypeScript typedefs from one or more schema JSON files
 * @param {string | string[]} sources - JSON schema source(s)
 * @param {URL | string} destination - Output destination
 */
const compileTypesFromSchemas = async (sources, destination) => {
  const sourceArray = Array.isArray(sources) ? sources : [sources];
  const parts = await Promise.all(sourceArray.map(compileSchemaFile));
  const ts = transformTS(parts.join('\n\n'));

  const file =
    destination instanceof URL ? destination : new URL(destination, root);

  await fs.writeFile(file, ts);

  // Type-check using the tsconfig.json colocated with the destination. The
  // root tsconfig excludes build/, so types/ and build/ each have their own
  // tsconfig that overrides skipLibCheck for the generated declarations.
  const projectDir = new URL('.', file);
  spawn('tsc', ['-p', fileURLToPath(projectDir)], {
    cwd: fileURLToPath(root),
    stdio: 'inherit',
  });
};

/**
 * Compile the public TypeScript typedefs
 * @param {string} [source] - JSON schema source
 * @param {URL | string} [destination] - Output destination
 * @returns {Promise<void>}
 */
export const compilePublicTypes = (
  source = 'schemas/public.schema.json',
  destination = 'types/public.d.ts',
) => compileTypesFromSchemas(source, destination);

/**
 * Compile the internal TypeScript typedefs
 * @param {URL | string} [destination] - Output destination
 * @returns {Promise<void>}
 */
export const compileInternalTypes = (destination = 'types/internal.d.ts') =>
  compileTypesFromSchemas(
    ['schemas/browsers.schema.json', 'schemas/compat-data.schema.json'],
    destination,
  );

/**
 * Cleans up old types.
 */
const cleanupObsolete = async () => {
  const path = new URL('types/types.d.ts', root);
  try {
    await rm(path);
  } catch {
    // Ignore.
  }
};

if (esMain(import.meta)) {
  await Promise.all([
    compileInternalTypes(),
    compilePublicTypes(),
    cleanupObsolete(),
  ]);
}

/* c8 ignore stop */
