/* This file is a part of @mdn/browser-compat-data
 * See LICENSE file for more information. */

import fs from 'node:fs/promises';

import esMain from 'es-main';
import { compileFromFile } from 'json-schema-to-typescript';

const opts = {
  bannerComment: '',
};

const compile = async () => {
  const browserTS = await compileFromFile('schemas/browsers.schema.json', opts);
  const compatTS = await compileFromFile(
    'schemas/compat-data.schema.json',
    opts,
  );

  const ts =
    '/* This file is a part of @mdn/browser-compat-data\n * See LICENSE file for more information. */\n\n/**\n* This file was automatically generated by json-schema-to-typescript.\n* DO NOT MODIFY IT BY HAND. Instead, modify the source schema files in\n* schemas/*, and run "npm run regen-types" to regenerate this file.\n*/\n\n' +
    browserTS +
    compatTS;

  await fs.writeFile(new URL('../types-autogen.d.ts', import.meta.url), ts);
};

if (esMain(import.meta)) {
  await compile();
}
