name: Add artifacts on push

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Enumerate and diff features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # get the full repository checkout, not just the inciting commit
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: npm
          package-manager-cache: true
      - run: npm ci
      - run: node ./scripts/enumerate-features.js features.json
      - run: node ./scripts/diff-features.js --no-github --format=json > features.diff.json
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: enumerate-features
          path: features.json
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: diff-features
          path: features.diff.json
