# Labels issues by BCD key, MDN URL or other regex match in issue description.
name: Issue Labeler
on:
  issues:
    types: [opened]

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-regex-labeler.yml
          enable-versioned-regex: 0
