# Labels issues by BCD key, MDN URL or other regex match in issue description.
name: Issue Labeler
on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  issue-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/issue-regex-labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
