name: Update web-features tags

on:
  pull_request_target:
    branches:
      - main
    paths:
      - "package-lock.json"

permissions:
  contents: write
  pull-requests: read

jobs:
  update-web-features:
    if: github.repository == 'mdn/browser-compat-data' && github.event.pull_request.user.login == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/npm_and_yarn/web-features-')
    name: Update web-features-tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}
          persist-credentials: true
          allow-unsafe-pr-checkout: true

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          package-manager-cache: false

      - name: Setup git
        run: |
          git config user.email 108879845+mdn-bot@users.noreply.github.com
          git config user.name mdn-bot

      - name: Install
        env:
          # Temporary workaround to install lefthook hooks.
          CI: ""
        run: npm ci

      - name: Update tags
        env:
          REF: ${{ github.head_ref }}
        run: |
          npm run lint:fix -- --only=web_features
          npm run lint -- --only=web_features --fail-on-warnings
          if git diff --exit-code; then
            echo "No changes."
          else
            git commit -m 'chore: update web-features tags' .
            git push origin "$REF"
          fi
